In [1]:
import glob
import scipy.misc
path = '/home/aiteam/tykim/HybrIK/data/3dhp/mpi_inf_3dhp_train_set/S2/Seq1/images/S2_Seq1_V1/*.jpg'

test = glob.glob(path)

import cv2

cv2.setNumThreads(0)
cv2.ocl.setUseOpenCL(False)

In [18]:
from numba import vectorize
import numpy as np
@vectorize(['int64(int64, int64)'], target='cuda')
def add_ufunc(x, y):
    return x + y

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
b_col = b[:, np.newaxis] # b as column array
c = np.arange(4*4).reshape((4,4))

print('a+b:\n', add_ufunc(a, b))
print()
print('b_col + c:\n', add_ufunc(b_col, c))

a+b:
 [11 22 33 44]

b_col + c:
 [[10 11 12 13]
 [24 25 26 27]
 [38 39 40 41]
 [52 53 54 55]]


/home/aiteam/miniconda3/envs/hybrik/lib/python3.7/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


: 

In [ ]:
class MyTransfrom(object):
  def __call__(self, img):
    